openapi: 3.2.0
info:
  title: Defined.ai Deliverables API
  description: '# Introduction


    Welcome to the Defined.ai Public API.'
  version: v2
  x-logo:
    url: https://definedcrowd.azureedge.net/content/images/dai-logo-black.svg
    backgroundColor: '#FFFFFF'
    href: https://defined.ai/
security:
- Bearer: []
tags:
- name: Deliverables
  description: The result file is created after the project is completed and is referred to as deliverables. The file contains contributor metadata for completed input units.
paths:
  /v2.0/public/projects/{projectId}/deliverables:
    get:
      tags:
      - Deliverables
      summary: Get Deliverables
      description: 'The function retrieves details, including metadata and the ID, for all available files

        of the given project ID.


        **Permission Required:** Read Project Properties'
      operationId: ProjectsDeliverables_GetDeliverables
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      - name: sortBy
        in: query
        description: 'Type of filter. Valid values: "createdTimestamp", "isPartial", "downloadCount", "fileName", "type".

          Please note that, it is only possible to use one filter at a time.'
        schema:
          type: string
          default: createdTimestamp
      - name: sortDirection
        in: query
        description: 'Order of displayed results. Valid values: "asc", "desc".'
        schema:
          type: string
          default: desc
      - name: pageNumber
        in: query
        description: The page to retrieve.
        schema:
          type: integer
          format: int32
          default: 0
      - name: itemsPerPage
        in: query
        description: The number of items to retrieve per page. The maximum number of items per page allowed is 100.
        schema:
          type: integer
          format: int32
          default: 10
      - name: type
        in: query
        description: The project deliverable type.
        schema:
          enum:
          - Classic
          - Aggregated
          - Flat
          - CrowdMetadata
          type: string
        x-enumNames:
        - Classic
        - Aggregated
        - Flat
        - CrowdMetadata
        x-enumDescriptions:
        - ''
        - ''
        - ''
        - ''
      - name: isPartial
        in: query
        description: Indication of whether the file contains partial result set or complete result set.
        schema:
          type: boolean
      responses:
        '200':
          description: Success.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.GetPagedProjectDeliverables'
            application/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.GetPagedProjectDeliverables'
            text/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.GetPagedProjectDeliverables'
        '400':
          description: Invalid parameters.
        '401':
          description: Invalid Authentication (invalid/expired token).
        '404':
          description: Project does not exist.
  /v2.0/public/projects/{projectId}/deliverables/{deliverableId}:
    get:
      tags:
      - Deliverables
      summary: Get Deliverable Details
      description: 'Retrieves a deliverable file with details on what will be provided for each project.


        **Permission Required:** Read Project Properties'
      operationId: ProjectsDeliverables_GetDeliverablesDetails
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      - name: deliverableId
        in: path
        description: Deliverable ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Success.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.ProjectDeliverable'
            application/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.ProjectDeliverable'
            text/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.ProjectDeliverable'
        '401':
          description: Invalid Authentication (invalid/expired token).
        '404':
          description: Project or deliverable does not exist.
  /v2.0/public/projects/{projectId}/deliverables/{deliverableId}/download:
    get:
      tags:
      - Deliverables
      summary: Get Deliverable Download
      description: 'Download the project deliverable file.


        **Permission Required:** Read Project Properties'
      operationId: ProjectsDeliverables_GetDeliverablesDownload
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      - name: deliverableId
        in: path
        description: Deliverable ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Success. The file is returned.
        '401':
          description: Invalid authentication (invalid/expired token).
        '404':
          description: Project or deliverable does not exist.
components:
  schemas:
    DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.ProjectDeliverable:
      title: JSON object
      type: object
      properties:
        projectId:
          type: string
          description: Project ID.
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        deliverableId:
          type: string
          description: Deliverable ID within a project.
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        type:
          type:
          - string
          - 'null'
          description: "\n**Classic**</br> is a standard JSON format generated by our API.  \n            \n**Aggregated**</br> is a format that combines results for all responses at the task level.\n            \n**Flat**</br> is a result file at the response level.  \n            \n**CrowdMetadata**</br> contains information about the contributors that are relevant to their results."
        fileName:
          type:
          - string
          - 'null'
          description: Name of the result file.
        createdTimestamp:
          type: string
          description: Date and timestamp of when the file was created.
          format: date-time
        isPartial:
          type: boolean
          description: Indication of whether the file contains partial result set or complete result set.
        downloadCount:
          type: integer
          description: Number of times file was downloaded.
          format: int32
      additionalProperties: false
    DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.GetPagedProjectDeliverables:
      title: JSON object
      type: object
      properties:
        deliverables:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.ProjectDeliverables.ProjectDeliverable'
          description: List of deliverables
        totalCount:
          type: integer
          description: Total number of items available.
          format: int32
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please enter into field the word 'Bearer' following by space and JWT
      name: Authorization
      in: header
x-tagGroups:
- name: ' '
  tags:
  - Supported Languages
- name: Project life cycle
  tags:
  - Project Management
  - Subscriptions
  - Jobs
  - Input Units
  - Deliverables
- name: Speech Technologies
  tags:
  - Mean Opinion Score
  - Pronunciation Validation
