openapi: 3.2.0
info:
  title: Defined.ai Jobs API
  description: '# Introduction


    Welcome to the Defined.ai Public API.'
  version: v2
  x-logo:
    url: https://definedcrowd.azureedge.net/content/images/dai-logo-black.svg
    backgroundColor: '#FFFFFF'
    href: https://defined.ai/
security:
- Bearer: []
tags:
- name: Jobs
  description: Jobs are how your data (input units) connects the project with our contributors. Each job has data, instructions, and customizable parameters, which then convert inputs to outputs. Parameters are customizable according to your project needs.
paths:
  /v2.0/public/projects/{projectId}/jobs:
    get:
      tags:
      - Jobs
      summary: Get Jobs
      description: 'Retrieves a list of job IDs within a specific project.


        **Permission Required:** Read Project Properties'
      operationId: Jobs_GetJobs
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: Success.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Jobs.GetProjectJobsResult'
            application/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Jobs.GetProjectJobsResult'
            text/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Jobs.GetProjectJobsResult'
        '400':
          description: Invalid parameters.
        '401':
          description: Invalid authentication (invalid/expired token).
        '404':
          description: Project does not exist.
  /v2.0/public/projects/{projectId}/jobs/{jobId}:
    put:
      tags:
      - Jobs
      summary: Edit Job
      description: 'The job settings are editable until the first input units are uploaded, which means when the project

        state is still NOT ACTIVE. For instance, change the number of contributors allowed for each input unit.


        **Permission Required:** Update Project Properties'
      operationId: Jobs_EditJob
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      - name: jobId
        in: path
        description: Job ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      requestBody:
        description: ''
        content:
          application/json-patch+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Jobs.UpdateProjectJobViewModel'
          application/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Jobs.UpdateProjectJobViewModel'
          text/json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Jobs.UpdateProjectJobViewModel'
          application/*+json:
            schema:
              allOf:
              - $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Jobs.UpdateProjectJobViewModel'
        required: true
      responses:
        '202':
          description: Accepted. Job is updated asynchronously. No response body.
        '400':
          description: Invalid parameters.
        '401':
          description: Invalid authentication (invalid/expired token).
        '404':
          description: Project or job does not exist.
components:
  schemas:
    DefinedCrowd.PublicApi.Api.Results.Jobs.Job:
      title: JSON object
      type: object
      properties:
        id:
          type: string
          description: Job identifier.
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
        contributorsPerInputUnit:
          type: integer
          description: Number of contributors needed to complete one input unit.
          format: int32
        languageCode:
          type:
          - string
          - 'null'
          description: Language code configured. (e.g. "en-us")
      additionalProperties: false
    DefinedCrowd.PublicApi.Api.Models.Jobs.UpdateProjectJobViewModel:
      title: JSON object
      required:
      - contributorsPerInputUnit
      type: object
      properties:
        contributorsPerInputUnit:
          maximum: 100
          minimum: 1
          type: integer
          description: Number of contributors needed to complete one input unit.
          format: int32
      additionalProperties: false
    DefinedCrowd.PublicApi.Api.Results.Jobs.GetProjectJobsResult:
      title: JSON object
      type: object
      properties:
        jobs:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Jobs.Job'
          description: List of jobs within a specific project
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please enter into field the word 'Bearer' following by space and JWT
      name: Authorization
      in: header
x-tagGroups:
- name: ' '
  tags:
  - Supported Languages
- name: Project life cycle
  tags:
  - Project Management
  - Subscriptions
  - Jobs
  - Input Units
  - Deliverables
- name: Speech Technologies
  tags:
  - Mean Opinion Score
  - Pronunciation Validation
