openapi: 3.2.0
info:
  title: Defined.ai Subscriptions API
  description: '# Introduction


    Welcome to the Defined.ai Public API.'
  version: v2
  x-logo:
    url: https://definedcrowd.azureedge.net/content/images/dai-logo-black.svg
    backgroundColor: '#FFFFFF'
    href: https://defined.ai/
security:
- Bearer: []
tags:
- name: Subscriptions
  description: Subscribe to automatic notifications for specific email addresses.
paths:
  /v2.0/public/projects/{projectId}/subscriptions:
    put:
      tags:
      - Subscriptions
      summary: Put Subscriptions
      description: 'Subscribe or edit the list of email addresses that receive the notifications.

        Currently, the following types of events are available for subscription:


        **Data Upload Completed:** Receive a notification when an upload of data for the project

        is completed, including information if any errors were found. The email is only sent after

        the asynchronous part of the upload is finished. Note that you will receive an email per each

        input unit set uploaded. You can know more

        in data upload section.


        **Deliverable Published:** Receive a notification when a new result file for the project is available to

        download. You can know more in the

        deliverables section.


        **Permissions:** Update Project Properties'
      operationId: Subscriptions_SubmitSubscriptions
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      requestBody:
        description: Subscriptions.
        content:
          application/json-patch+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Subscriptions.SubscriptionViewModel'
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Subscriptions.SubscriptionViewModel'
          text/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Subscriptions.SubscriptionViewModel'
          application/*+json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Models.Subscriptions.SubscriptionViewModel'
      responses:
        '202':
          description: Accepted. Subscription will be configured asynchronously.
        '400':
          description: Invalid parameters.
        '401':
          description: Invalid authentication (invalid/expired token).
        '403':
          description: Email consent is missing (or invalid), subscription can’t be done without email consent.
        '404':
          description: Project does not exist.
    get:
      tags:
      - Subscriptions
      summary: Get Subscriptions
      description: 'Retrieves a list of subscribed notifications within a specific project.


        **Permissions:** Read Project Properties'
      operationId: Subscriptions_GetSubscriptions
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      responses:
        '200':
          description: OK. Returns a list with project subscriptions.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Subscriptions.GetSubscriptionsResults'
            application/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Subscriptions.GetSubscriptionsResults'
            text/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Subscriptions.GetSubscriptionsResults'
        '401':
          description: Invalid authentication (invalid/expired token).
        '404':
          description: Project does not exist.
  /v2.0/public/projects/{projectId}/subscriptions/{type}:
    delete:
      tags:
      - Subscriptions
      summary: Delete Subscription
      description: 'Allows to unsubscribe each of the existing notifications.


        **Permissions**: Update Project Properties'
      operationId: Subscriptions_DeleteSubscription
      parameters:
      - name: projectId
        in: path
        description: Project ID.
        required: true
        schema:
          type: string
          format: uuid
          example: 00000000-0000-0000-0000-000000000000
      - name: type
        in: path
        description: 'Type of notifications. Valid values: "DeliverablePublished" and "DataUploadCompleted".'
        required: true
        schema:
          type: string
      responses:
        '202':
          description: Accepted. Subscription will be deleted asynchronously.
        '400':
          description: Invalid parameters.
        '401':
          description: Invalid authentication (invalid/expired token).
        '404':
          description: Project does not exist / Subscription type is not configured.
components:
  schemas:
    DefinedCrowd.PublicApi.Api.Results.Subscriptions.GetSubscriptionsResults:
      title: JSON object
      type: object
      properties:
        subscriptions:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Subscriptions.Dtos.SubscriptionResult'
          description: List of subscriptions.
        totalCount:
          type: integer
          description: Total number of items available.
          format: int32
      additionalProperties: false
    DefinedCrowd.PublicApi.Api.Results.Subscriptions.Dtos.SubscriptionResult:
      title: JSON object
      type: object
      properties:
        type:
          enum:
          - DeliverablePublished
          - DataUploadCompleted
          type: string
          description: Type of notifications.
          x-enumNames:
          - DeliverablePublished
          - DataUploadCompleted
          x-enumDescriptions:
          - ''
          - ''
          x-ms-enum:
            name: NotificationType
            modelAsString: true
        to:
          type:
          - array
          - 'null'
          items:
            type: string
          description: List of main recipients of the email addresses [1-10]
        emailListConsent:
          type: boolean
          description: 'When this flag is True the user acknowledges that it has obtained all necessary valid consents

            from the relevant data subjects (email owners) to subscribe, on their behalf, each respective email address

            to this notification service, in compliance with the applicable data protection laws, and in agreement with

            Defined.ai''s service <a href="https://www.defined.ai/terms-of-use">Terms of Use</a>

            and <a href="https://www.defined.ai/privacy-policy">Privacy Policy</a>.'
      additionalProperties: false
    DefinedCrowd.PublicApi.Api.Models.Subscriptions.SubscriptionViewModel:
      title: JSON object
      required:
      - emailListConsent
      - to
      - type
      type: object
      properties:
        type:
          minLength: 1
          type: string
          description: 'Type of notifications. Valid values: "DeliverablePublished" and "DataUploadCompleted".'
        to:
          type: array
          items:
            type: string
          description: List of main recipients of the email addresses [1-10].
        emailListConsent:
          type: boolean
          description: 'By setting this flag to True the user acknowledges that it has obtained all necessary valid consents from

            the relevant data subjects (email owners) to subscribe, on their behalf, each respective email address to

            this notification service, in compliance with the applicable data protection laws, and in agreement with

            Defined.ai''s service <a href="https://www.defined.ai/terms-of-use">Terms of Use</a>

            and <a href="https://www.defined.ai/privacy-policy">Privacy Policy</a>.'
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please enter into field the word 'Bearer' following by space and JWT
      name: Authorization
      in: header
x-tagGroups:
- name: ' '
  tags:
  - Supported Languages
- name: Project life cycle
  tags:
  - Project Management
  - Subscriptions
  - Jobs
  - Input Units
  - Deliverables
- name: Speech Technologies
  tags:
  - Mean Opinion Score
  - Pronunciation Validation
