openapi: 3.2.0
info:
  title: Defined.ai Supported Languages API
  description: '# Introduction


    Welcome to the Defined.ai Public API.'
  version: v2
  x-logo:
    url: https://definedcrowd.azureedge.net/content/images/dai-logo-black.svg
    backgroundColor: '#FFFFFF'
    href: https://defined.ai/
security:
- Bearer: []
tags:
- name: Supported Languages
  description: Several of the Workflow Templates offer the ability to set a language / country code. These configurations instruct Defined.ai to use our human intelligence Contributors that speak and / or reside in the specified language / country. The REST API provides a method called “Get Supported Languages” that returns the set of languages, language features and associated language codes that are used by our APIs and supported by the Defined.ai platform.
paths:
  /v2.0/public/languages:
    get:
      tags:
      - Supported Languages
      summary: Get supported languages
      description: '|The endpoint will be deprecated


        Returns a list of language and country combinations supported by Defined.ai, the language code associated

        with each combination, and whether Defined.ai supports the ability to source for a specific language’s

        native speakers, all of whom have passed a series of language tests administered by Defined.ai.


        The Language code may be added to the Configuration of a Project. If you need to source high-quality data

        from native speakers, the value nativeSpeakerSupported will indicate whether Defined.ai supports that

        capability the specific language you’re looking for.


        The number of languages we support varies.


        Defined.ai currently supports the following languages:


        | **Language** | **Country** | **Language Code + Country** |

        |:------------:|:-----------:|:---------------------------:|

        | **Arabic**| Egypt | ar-EG |

        | **Arabic**| Jordan | ar-JO |

        | **Arabic**| Morocco | ar-MA |

        | **Arabic**| Saudi Arabia | ar-SA |

        | **Arabic**| United Arab Emirates | ar-AE |

        | **Arabic**| Yemen | ar-YE |

        | **Basque**| Spain | eu-ES |

        | **Bengali**| India | bn-IN |

        | **Catalan**| Spain | ca-ES |

        | **Chinese Simplified**| China (Mandarin) | zh-CN |

        | **Chinese Simplified**| Singapore (Mandarin) | zh-SG |

        | **Chinese Traditional**| Taiwan (Mandarin) | zh-TW |

        | **Chinese Traditional**| Hong Kong (Cantonese) | zh-HK |

        | **Croatian**| Croatia | hr-HR |

        | **Czech**| Czech Republic | cs-CZ |

        | **Danish**| Denmark | da-DK |

        | **Danish**| Greenland | da-GL |

        | **Dutch**| Netherlands | nl-NL |

        | **Dutch**| Belgium (Flemish) | nl-BE |

        | **English**| United Kingdom | en-GB |

        | **English**| United States | en-US |

        | **English**| Canada | en-CA |

        | **English**| Philippines | en-PH |

        | **English**| Singapore | en-SG |

        | **English**| Australia | en-AU |

        | **English**| New Zealand | en-NZ |

        | **English**| India | en-IN |

        | **English**| Ireland | en-IE |

        | **English**| South Africa | en-ZA |

        | **Estonian**| Estonia | et-EE |

        | **Finnish**| Finland | fi-Fl |

        | **French**| France | fr-FR |

        | **French**| Belgium | fr-BE |

        | **French**| Canada | fr-CA |

        | **Galician**| Spain | gl-ES |

        | **German**| Germany | de-DE |

        | **German**| Belgium | de-BE |

        | **German**| Austria | de-AT |

        | **German**| Switzerland | de-CH |

        | **Greek**| Greece | el-GR |

        | **Gujarati**| India | gu-IN |

        | **Hebrew**| Israel | he-IL |

        | **Hindi**| India | hi-IN |

        | **Hungarian**| Hungary | hu-HU |

        | **Indonesian (Bahasa)**| Indonesia | id-ID |

        | **Irish**| Ireland | ga-IE |

        | **Italian**| Italy | it-IT |

        | **Japanese**| Japan | ja-JP |

        | **Kannada**| India | ml-IN |

        | **Korean**| South Korea | ko-KR |

        | **Latvian**| Latvia | lv-LV |

        | **Lithuanian**| Lithuania | lt-LT |

        | **Malay**| Malaysia | ms-MY |

        | **Malayalam**| India | ml-IN |

        | **Marathi**| India | mr-IN |

        | **Norwegian Bokmål**| Norway | nb-NO |

        | **Persian / Farsi**| Iran | fa-IR |

        | **Polish**| Poland | pl-PL |

        | **Portuguese**| Portugal | pt-PT |

        | **Portuguese**| Brazil | pt-BR |

        | **Portuguese**| Angola | pt-AO |

        | **Portuguese**| Mozambique | pt-MZ |

        | **Punjabi**| India | pa-IN |

        | **Romanian**| Romania | ro-RO |

        | **Russian**| Russia | ru-RU |

        | **Slovak**| Slovakia | sk-SK |

        | **Slovenian**| Slovenia | sl-SI |

        | **Spanish**| Spain | es-ES |

        | **Spanish**| Argentina | es-AR |

        | **Spanish**| Chile | es-CL |

        | **Spanish**| Colombia | es-CO |

        | **Spanish**| Mexico | es-MX |

        | **Spanish**| Peru | es-PE |

        | **Spanish**| Paraguay | es-PY |

        | **Spanish**| United States | es-US |

        | **Spanish**| Venezuela | es-VE |

        | **Swedish**| Sweden | sv-SE |

        | **Tamil**| Singapore | ta-SG |

        | **Telugu**| India | te-IN |

        | **Thai**| Thailand | th-TH |

        | **Turkish**| Turkey | tr-TR |

        | **Ukrainian**| Ukraine | uk-UA |

        | **Urdu**| India | ur-IN |

        | **Vietnamese**| Vietnam | vi-VN |


        **Permission Required:** None'
      operationId: Languages_GetLanguages
      responses:
        '200':
          description: Returns a list with the language information.
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Languages.GetLanguagesResults'
            application/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Languages.GetLanguagesResults'
            text/json:
              schema:
                $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Languages.GetLanguagesResults'
        '401':
          description: Invalid authentication (invalid/expired token).
        '403':
          description: Invalid Enterprise Subscription.
      deprecated: true
components:
  schemas:
    DefinedCrowd.PublicApi.Api.Results.Languages.LanguageInfo:
      title: JSON object
      type: object
      properties:
        language:
          type:
          - string
          - 'null'
          description: Language name.
        languageCode:
          type:
          - string
          - 'null'
          description: Language code.
        country:
          type:
          - string
          - 'null'
          description: Country name.
        nativeSpeakerSupported:
          type: boolean
          description: Support for sourcing of native speakers.
      additionalProperties: false
    DefinedCrowd.PublicApi.Api.Results.Languages.GetLanguagesResults:
      title: JSON object
      type: object
      properties:
        languages:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/DefinedCrowd.PublicApi.Api.Results.Languages.LanguageInfo'
          description: List of supported languages.
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: Please enter into field the word 'Bearer' following by space and JWT
      name: Authorization
      in: header
x-tagGroups:
- name: ' '
  tags:
  - Supported Languages
- name: Project life cycle
  tags:
  - Project Management
  - Subscriptions
  - Jobs
  - Input Units
  - Deliverables
- name: Speech Technologies
  tags:
  - Mean Opinion Score
  - Pronunciation Validation
